apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bfc5f3-app-prod
spec:
  destination:
    name: ''
    namespace: bfc5f3-prod
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/gitops
    repoURL: 'git@github.com:bcgov-c/tenant-gitops-bfc5f3.git'
    targetRevision: main
    helm:
      valueFiles:
        - $values/deploy/prod_values.yaml
  project: bfc5f3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true